-- ============================================================
-- SUS Predict — perfis, RBAC Admin, RLS e auditoria
-- Execute depois de supabase/schema.sql no SQL Editor.
-- Este script é idempotente e NÃO promove usuários automaticamente.
-- ============================================================

begin;

do $$
begin
  create type public.app_role as enum ('admin');
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  job_title text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_full_name_length check (char_length(full_name) <= 120),
  constraint profiles_job_title_length check (char_length(job_title) <= 120)
);

create table if not exists public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.app_role not null,
  granted_by uuid references auth.users(id) on delete set null,
  granted_at timestamptz not null default now(),
  primary key (user_id, role)
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_user_id uuid references auth.users(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists user_roles_user_id_idx
  on public.user_roles (user_id);
create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, job_title)
  values (
    new.id,
    left(coalesce(new.raw_user_meta_data ->> 'full_name', ''), 120),
    left(coalesce(new.raw_user_meta_data ->> 'job_title', ''), 120)
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_auth_user();

-- Usuários anteriores à migration também recebem perfil, mas nunca role.
insert into public.profiles (id, full_name, job_title)
select
  users.id,
  left(coalesce(users.raw_user_meta_data ->> 'full_name', ''), 120),
  left(coalesce(users.raw_user_meta_data ->> 'job_title', ''), 120)
from auth.users as users
on conflict (id) do nothing;

create or replace function public.has_role(requested_role public.app_role)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = (select auth.uid())
      and role = requested_role
  );
$$;

revoke all on function public.has_role(public.app_role) from public;
grant execute on function public.has_role(public.app_role) to authenticated;

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.admin_audit_log enable row level security;

revoke all on table public.profiles from anon;
revoke all on table public.user_roles from anon;
revoke all on table public.admin_audit_log from anon;

grant select on table public.profiles to authenticated;
grant select on table public.user_roles to authenticated;
grant select on table public.admin_audit_log to authenticated;

drop policy if exists profiles_select_self_or_admin on public.profiles;
create policy profiles_select_self_or_admin
on public.profiles
for select
to authenticated
using (
  id = (select auth.uid())
  or (select public.has_role('admin'::public.app_role))
);

drop policy if exists user_roles_select_self_or_admin on public.user_roles;
create policy user_roles_select_self_or_admin
on public.user_roles
for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select public.has_role('admin'::public.app_role))
);

drop policy if exists admin_audit_select_admin on public.admin_audit_log;
create policy admin_audit_select_admin
on public.admin_audit_log
for select
to authenticated
using ((select public.has_role('admin'::public.app_role)));

-- As tabelas de negócio são acessíveis diretamente somente a Admin autenticado.
-- O backend usa uma chave administrativa e, por isso, também valida JWT + role.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'datasus_runs',
    'datasus_raw_objects',
    'datasus_serie',
    'datasus_sexo',
    'datasus_faixa_etaria',
    'datasus_top_causas'
  ]
  loop
    if to_regclass('public.' || table_name) is not null then
      execute format('alter table public.%I enable row level security', table_name);
      execute format('revoke all on table public.%I from anon', table_name);
      execute format('grant select, insert, update, delete on table public.%I to authenticated', table_name);
      execute format('drop policy if exists admin_all on public.%I', table_name);
      execute format(
        'create policy admin_all on public.%I for all to authenticated '
        || 'using ((select public.has_role(''admin''::public.app_role))) '
        || 'with check ((select public.has_role(''admin''::public.app_role)))',
        table_name
      );
    end if;
  end loop;
end
$$;

commit;

-- PROMOÇÃO INICIAL (execute separadamente, trocando o e-mail):
--
-- insert into public.user_roles (user_id, role)
-- select id, 'admin'::public.app_role
-- from auth.users
-- where lower(email) = lower('seu-admin@exemplo.com')
-- on conflict (user_id, role) do nothing;
